### ISSUE TITLE
java -jar server-1.0-SNAPSHOT.jar throws java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by ramarajuv** [DomHeal/JavaFX-Chat#3]
Hi,

I downloaded the code, executed `mvn install` and then executed the server jar file from the maven repository. It throws the below error:

`java -jar server-1.0-SNAPSHOT.jar`:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.server.Server.<clinit>(Server.java:25)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more`

I have not modified anything on the pom.xml(s). Just cloned and installed.

However, the same command for client's jar file runs fine and loads the login screen. But as the server is not running, I am unable to use the application. Could you please provide assistance?

Thank you in advance.

**Comment by DomHeal** [comment]
Hi ramarajav,

Thanks for taking an interesting in my project, 

It seems there's an issue where it can find the slf4j library. The only way I have got around this issue, is by creating a fat jar file using the maven assembly plugin. 

If you pull my latest update to the server pom.xml file and run mvn install again, you will see an additional jar called server-1.0-SNAPSHOT-jar-with-dependencies. This should work correctly as it will compile the slf4j library in with the jar. This can be a used a work around for the time being.

Let me know if this helps you,

Thank you,

**Comment by ramarajuv** [comment]
@DomHeal Thank you for your response. The server seems to be working now, but the client still can't connect to the Server. It too throws a ClassNotFoundException for LoggerFactory.  Did you happen to run the version on your local machine with a complete clean and package mvn builds?

I am going to try updating client's pom.xml similar to the server's and see if that helps.

**Comment by DomHeal** [comment]
This seems like its the same issue as what is happening with the server. SLF4J is a bit of a pain to get working correctly. I will do the plugin change for the client also to fix this for the time being. I'll commit the changes later today. This seems like a common issue for SLF4J. Updating the client pom to the same as the sever pom should let you carry on.
